name: Deploy Vue Project

on:
  push:
    branches:
      - main
    paths:
      - 'vue-project/**'
      - '.github/workflows/deploy.yml'

# 重要：增加权限
permissions:
  contents: write  # 必须要有写入权限
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # 声明使用GitHub Pages环境
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'vue-project/package-lock.json'

      # 准备数据文件（移到构建步骤之后）
      - name: Prepare data and image files
        run: |
          mkdir -p vue-project/public/data
          
          # 清理任何预存符号链接
          find vue-project/public/data -type l -delete 2>/dev/null || true
          rm -f vue-project/public/data/*.json 2>/dev/null || true
          rm -rf vue-project/public/data/images 2>/dev/null || true
          
          # 创建干净的images目录
          mkdir -p vue-project/public/data/images
          
          # 安全复制JSON文件
          if [[ -f "nikkes.json" && ! -L "nikkes.json" ]]; then
              cp nikkes.json vue-project/public/data/
          else
              echo "警告: nikkes.json 不可用或为符号链接"
          fi
          
          if [[ -f "nikkes_add.json" && ! -L "nikkes_add.json" ]]; then
              cp nikkes_add.json vue-project/public/data/
          else
              echo "警告: nikkes_add.json 不可用或为符号链接"
          fi
          
          # 安全复制图片
          if [ -d "images" ]; then
              cp -r --no-dereference images/. vue-project/public/data/images/
              echo "成功复制 $(find vue-project/public/data/images -type f | wc -l) 张图片"
          else
              echo "警告: images 目录未找到"
          fi
          
          # 详细验证
          echo "最终目录结构:"
          tree -L 3 vue-project/public/data || true

      - name: Install dependencies
        working-directory: ./vue-project
        run: npm ci

      - name: Build project
        working-directory: ./vue-project
        run: npm run build

      # 使用官方推荐部署流程
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./vue-project/dist

      # 使用官方部署（替换peaceiris方案）
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4