name: Deploy Vue Project

on:
  push:
    branches:
      - main  # 触发分支
    paths:
      - 'vue-project/**'  # 仅监控子目录变动

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # 按需修改版本

      - name: Install dependencies
        working-directory: ./vue-project  # 进入子目录
        run: npm ci  # 精准安装依赖

      - name: Build project
        working-directory: ./vue-project
        run: npm run build  # 执行构建命令

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./vue-project/dist  # 构建产物目录